### ISSUE TITLE
btc htlc: replace depreceated `generate`

### ISSUE THREAD

**Issue by takahser** [Trinkler/trade-swap#23]
Please provide the following information:

### Expected behaviour

- tests run successfully without bitcoin core running on the `-deprecatedrpc=generate` parameter

### Actual behaviour

-  bitcoin core (bitcoind) has to be run as follow: `bitcoind -regtest -server -rpcuser=user -rpcpassword=pass -rpcport=18332 -txindex -deprecatedrpc=generate`
- if we skip the param, it displays an error:

```
RpcError: -32 The wallet generate rpc method is deprecated and will be fully removed in v0.19. To use generate in v0.18, restart bitcoind with -deprecatedrpc=generate.
Clients should transition to using the node rpc method generatetoaddress
```

- currently, bitcoind is on v17.x
- from v19.x, `generate` will be completely removed

### Information about our environment

see also: https://github.com/bitcoin/bitcoin/issues/14299

**Comment by retotrinkler** [comment]
Closing as acceptable drawback
